name: "JavaScript Test Action"
description: "JavaScript Test Action"
author: "Shane"
branding:
  icon: "type"
  color: "green"

inputs:
  tag:
    description: "Tag to Create or Update"
    default: "test"
    required: false
  summary:
    description: "Add Summary to Job"
    default: "true"
    required: false
  token:
    description: "GitHub Token"
    default: ${{ github.token }}
    required: false

outputs:
  sha:
    description: "Tag Hash"

runs:
  using: "node20"
  main: "dist/index.js"
