name: "JavaScript Test Action"
description: "JavaScript Test Action"
author: "Shane"
branding:
  icon: "type"
  color: "green"

inputs:
  tag:
    description: "Tag to Create or Update"
    required: false
    default: "test"
  summary:
    description: "Add Summary to Job"
    required: false
    default: "true"
  token:
    description: "GitHub Token"
    required: false
    default: ${{ github.token }}

outputs:
  sha:
    description: "Tag Hash"

# https://www.schemastore.org/github-action.json
runs:
  using: "node24"
  main: "dist/index.js"
