name: "Check Build"

on:
  pull_request_target:
    paths:
      - "dist/**"
      - "src/**"
      - "package*.json"
      - "rollup.config.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-build:
    name: "Check Build"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: "Debug CTX github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Checkout Pull"
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "Debug"
        continue-on-error: true
        run: |
          echo "::group::ls"
          ls -lAh
          echo "::endgroup::"
          echo "::group::tree"
          tree .
          echo "::endgroup::"

      - name: "Check Build Action"
        uses: cssnr/check-build-action@v1
