---
name: "MegaLinter"

on:
  push:
  #pull_request:

concurrency:
  group: megalinter
  cancel-in-progress: true

permissions: {}

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Actionlint"
        id: get_actionlint
        run: |
          tag=$(curl -sI https://github.com/rhysd/actionlint/releases/latest | grep -i ^location: | sed -E 's#.*/tag/v(.*)#\1#')
          echo "tag: ${tag}"
          url="https://github.com/rhysd/actionlint/releases/latest/download/actionlint_${tag//[$'\t\r\n']}_linux_amd64.tar.gz"
          echo "url: ${url}"
          curl -sL "${url}" | tar xvz -C "${RUNNER_TEMP}" actionlint
          file "${RUNNER_TEMP}/actionslint"
          "${RUNNER_TEMP}/actionslint" -color
