---
name: "MegaLinter"

on:
  push:
  #pull_request:

concurrency:
  group: megalinter
  cancel-in-progress: true

permissions: {}

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Download actionlint"
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: "Check workflow files"
        run: ${{ steps.get_actionlint.outputs.executable }} -color
