name: "Test"

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "18 18 * * 1,3,5"
  push:
    branches: ["**"]
    paths:
      - "dist/**"
      - "src/**"
      - ".github/workflows/test.yaml"
      - "package*.json"
      - "requirements.txt"
      - "action.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug event.json"
        continue-on-error: true
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          tag: "test"

      - name: "Verify Outputs"
        run: |
          echo "sha: '${{ steps.test.outputs.sha }}'"
          if [ -z '${{ steps.test.outputs.sha }}' ];then
            echo "No Output: sha"
            exit 1
          fi

      - name: "Schedule Failure Notification"
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
